// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ptowen
double ptowen(double q, int nu, double delta);
RcppExport SEXP _OwenQ128_ptowen(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ptowen(q, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// OwenQ1
double OwenQ1(int nu, double t, double delta, double R);
RcppExport SEXP _OwenQ128_OwenQ1(SEXP nuSEXP, SEXP tSEXP, SEXP deltaSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(OwenQ1(nu, t, delta, R));
    return rcpp_result_gen;
END_RCPP
}
// powen4
double powen4(int nu, double t1, double t2, double delta1, double delta2);
RcppExport SEXP _OwenQ128_powen4(SEXP nuSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP delta1SEXP, SEXP delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< double >::type delta2(delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(powen4(nu, t1, t2, delta1, delta2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OwenQ128_ptowen", (DL_FUNC) &_OwenQ128_ptowen, 3},
    {"_OwenQ128_OwenQ1", (DL_FUNC) &_OwenQ128_OwenQ1, 4},
    {"_OwenQ128_powen4", (DL_FUNC) &_OwenQ128_powen4, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_OwenQ128(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
