# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ptowen <- function(q, nu, delta) {
    .Call(`_OwenQ128_ptowen`, q, nu, delta)
}

OwenQ1 <- function(nu, t, delta, R) {
    .Call(`_OwenQ128_OwenQ1`, nu, t, delta, R)
}

